[package]
name = "strata_vault"
edition = "2024.beta"
version = "0.1.0"

[dependencies]
deepbook_predict = { git = "https://github.com/MystenLabs/deepbookv3.git", subdir = "packages/predict", rev = "predict-testnet-4-16"}