# M7 deploy script — Strata vault testnet publish (Windows PowerShell)
#
# Reproducible one-shot deploy to Sui testnet. Run from contracts/
# repo root after the worker's testnet keypair is funded with SUI gas
# (see docs/move_m7_notes.md LOCAL).
#
# Per docs/move_brief.md task M7 acceptance criteria:
#   1. sui client publish succeeds.
#   2. Package address is captured.
#   3. Deploy tx digest is captured.
#   4. Bytecode hash is captured for README cross-link.
#   5. Fresh testnet keypair (NOT Albary's mainnet wallet) is used.
#
# Usage:
#   pwsh -File scripts/deploy_testnet.ps1
#
# Output:
#   - Prints package_id, deploy_tx_digest, gas_used to stdout.
#   - Writes a JSON receipt to data/deploy_receipt.json (NOT tracked).

$ErrorActionPreference = 'Stop'

# --- 0. Sanity checks ---------------------------------------------------

Write-Host '=== M7 deploy preflight ==='
sui client active-env
$env = sui client active-env
if ($env -notmatch 'testnet') {
    Write-Error "[FAIL] active-env is not testnet (got: $env). Run 'sui client switch --env testnet' first."
    exit 1
}

$active = sui client active-address
Write-Host "active-address: $active"

$bal = sui client balance --json | ConvertFrom-Json
$totalSui = 0
foreach ($entry in $bal) {
    if ($entry.coinType -match 'SUI') {
        foreach ($coin in $entry.coinObjectIds) {
            $totalSui += [int64]$coin
        }
    }
}
Write-Host '--- balance entries (raw) ---'
$bal | Format-Table -AutoSize

# Minimum gas budget for a publish: ~1.5 SUI (1.5 * 10^9 MIST).
# Conservative floor: require at least 2 SUI in the active address.
$gasMinMist = 2_000_000_000
$sui = sui client gas --json | ConvertFrom-Json
$totalGas = ($sui | Measure-Object -Property mistBalance -Sum).Sum
Write-Host "total SUI gas balance: $totalGas MIST (need >= $gasMinMist)"
if ($null -eq $totalGas -or $totalGas -lt $gasMinMist) {
    Write-Error '[FAIL] insufficient gas. Fund the active address via https://faucet.sui.io/?address={active} before re-running.'
    exit 1
}

# --- 1. Build (sanity) --------------------------------------------------

Write-Host '=== M7 build + test gate ==='
sui move build
if ($LASTEXITCODE -ne 0) { Write-Error '[FAIL] sui move build failed.'; exit 1 }
sui move test
if ($LASTEXITCODE -ne 0) { Write-Error '[FAIL] sui move test failed.'; exit 1 }

# --- 2. Publish ----------------------------------------------------------

Write-Host '=== M7 sui client publish ==='
$pubOut = sui client publish --gas-budget 200_000_000 --json
if ($LASTEXITCODE -ne 0) { Write-Error '[FAIL] sui client publish failed.'; exit 1 }
$pub = $pubOut | ConvertFrom-Json

# Extract package_id from the publish output. The package object has
# objectType == 'package'.
$pkg = ($pub.objectChanges | Where-Object { $_.type -eq 'published' })[0]
$packageId = $pkg.packageId
$txDigest = $pub.digest

# Extract the shared Vault object id (the `Vault` struct shared at init).
$vaultObj = ($pub.objectChanges | Where-Object {
    $_.type -eq 'created' -and $_.objectType -match 'vault::Vault'
})[0]
$vaultId = $null
if ($vaultObj) { $vaultId = $vaultObj.objectId }

Write-Host ''
Write-Host '=== M7 deploy SUCCESS ==='
Write-Host "package_id      : $packageId"
Write-Host "deploy_tx_digest: $txDigest"
Write-Host "vault_object_id : $vaultId"

# --- 3. Receipt ---------------------------------------------------------

$dataDir = Join-Path $PSScriptRoot '..\data'
New-Item -ItemType Directory -Force -Path $dataDir | Out-Null
$receipt = [pscustomobject]@{
    package_id        = $packageId
    deploy_tx_digest  = $txDigest
    vault_object_id   = $vaultId
    deployer_address  = $active
    deploy_timestamp  = (Get-Date -Format 'o')
    env               = 'testnet'
    sui_cli_version   = (sui --version)
    notes             = 'Generated by scripts/deploy_testnet.ps1 per docs/move_brief.md M7.'
}
$receiptPath = Join-Path $dataDir 'deploy_receipt.json'
$receipt | ConvertTo-Json -Depth 5 | Out-File -FilePath $receiptPath -Encoding utf8
Write-Host "receipt written : $receiptPath"
Write-Host ''
Write-Host 'Next: paste package_id + tx_digest into contracts/README.md (M9) +'
Write-Host '      run scripts/replay_testnet.ps1 (M8) for sim-vs-onchain replay.'
