#!/usr/bin/env bash
# extract_publish_output.sh — pull the 3 fields the worker needs from
# `sui client publish --json` output.
#
# Usage:
#   sui client publish --gas-budget 500000000 --json > publish_output.json 2>&1
#   bash scripts/extract_publish_output.sh publish_output.json
#
# Prints (in worker paste-back format):
#   package_id        : 0x...
#   deploy_tx_digest  : <base58 digest>
#   vault_object_id   : 0x...
#
# Also writes `data/deploy_receipt.json` so the worker can fill the
# public README + cut the M9.7 tag from a single canonical source.

set -euo pipefail

INPUT="${1:-publish_output.json}"
if [[ ! -f "$INPUT" ]]; then
    echo "[FAIL] $INPUT missing — run sui client publish first."
    exit 1
fi

# Verify the file is valid JSON (publish errored if not).
if ! python3 -c "import sys, json; json.load(open(sys.argv[1]))" "$INPUT" 2>/dev/null; then
    echo "[FAIL] $INPUT is not valid JSON. First 40 lines:"
    head -40 "$INPUT"
    echo
    echo "[hint] If the file starts with 'The package has unpublished'"
    echo "       → Move.toml dep-override didn't take. Re-run"
    echo "         rm -rf build/ Move.lock && sui move build"
    echo "         before re-publishing. Worker's hotfix v2 (override=true)"
    echo "         is at commit 9b26f48."
    exit 1
fi

# Extract the 3 fields via Python (sui CLI output JSON is large enough
# that jq one-liners get unwieldy).
python3 <<PYEOF
import json, sys, datetime, pathlib

with open("$INPUT") as f:
    d = json.load(f)

# package_id from objectChanges with type=published
pkg = next(
    (c for c in d.get("objectChanges", []) if c.get("type") == "published"),
    None,
)
if pkg is None:
    print("[FAIL] no 'published' object in objectChanges — publish may have failed.")
    sys.exit(1)

package_id = pkg.get("packageId")
tx_digest = d.get("digest")

# Vault shared object: the one whose objectType contains 'vault::Vault'
vault_obj = next(
    (
        c for c in d.get("objectChanges", [])
        if c.get("type") == "created"
        and "vault::Vault" in c.get("objectType", "")
    ),
    None,
)
vault_id = vault_obj.get("objectId") if vault_obj else None

deployer = d.get("transaction", {}).get("data", {}).get("sender") or "<missing>"

print()
print("=== M7 deploy fields (paste THESE three lines to worker) ===")
print(f"package_id        : {package_id}")
print(f"deploy_tx_digest  : {tx_digest}")
print(f"vault_object_id   : {vault_id}")
print()

# Write canonical receipt.
receipt = {
    "package_id": package_id,
    "deploy_tx_digest": tx_digest,
    "vault_object_id": vault_id,
    "deployer_address": deployer,
    "deploy_timestamp": datetime.datetime.utcnow().isoformat() + "Z",
    "env": "testnet",
    "notes": "Generated by scripts/extract_publish_output.sh per M7 manual-publish flow.",
}
out = pathlib.Path("data/deploy_receipt.json")
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(json.dumps(receipt, indent=2))
print(f"[wrote] {out}")
PYEOF
